export const CartActionTypes = {
    ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
    GET_CART_PRODUCTS: "GET_CART_PRODUCTS",
    CART_ERROR: "CART_ERROR",
    DELETE_CART_PRODUCT: "DELETE_CART_PRODUCT",
    CART_CHECKOUT: "CART_CHECKOUT"
}