export const QuestionActionTypes = {
    GET_QUESTIONS: "GET_QUESTIONS",
    ASK_QUESTION: "ASK_QUESTION",
    QUESTION_ERROR: "QUESTION_ERROR",
    DELETE_QUESTION: "DELETE_QUESTION",
    UPDATE_QUESTION: "UPDATE_QUESTION"
}