export const ProductActionTypes = {
    ADD_PRODUCT: "ADD_PRODUCT",
    PRODUCT_ERROR: "PRODUCT_ERROR",
    GET_PRODUCTS: "GET_PRODUCTS",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    GET_PRODUCT: "GET_PRODUCT"
}